### ISSUE TITLE
Macros don't work in docstrings

### ISSUE THREAD

**Issue by foosel** [OctoPrint/docs#3]
Including macros like

```
{{ version_added("1.3.0") }}
```

into docstrings doesn't work, they won't render. 

*edit* figures work after all, indentation mistake on my part

**Comment by cp2004** [comment]
I wonder if maybe the docstrings (when rendered by mkdocstrings) don't get rendered by Jinja2 like the other stuff does.

*Edited*: Some research, my guess was correct https://github.com/mkdocstrings/mkdocstrings/discussions/441. The macros are rendered before the docstrings, so macros-in-docstrings don't work.

**Comment by cp2004** [comment]
An option if macros don't work might be a Python markdown plugin, which would not be too complex:
```python
from markdown.inlinepatterns import Pattern
from markdown.extensions import Extension
import xml.etree.ElementTree as etree

VERSION_RE = r"\[{2}\s*version(added|changed)(.*)\]{2}"

class VersionPattern(Pattern):
    def handleMatch(self, m):
        el = etree.Element("em")
        # Could link version to changelog?
        el.text = f"{m.group(2).capitalize()} in version {m.group(3).strip()}"
        return el

class VersionExtension(Extension):
    def extendMarkdown(self, md):
        pattern = VersionPattern(VERSION_RE)
        md.inlinePatterns.register(pattern, "version", 20)  # 20 is priority, not sure what it should be

def makeExtension(**kwargs):
    return VersionExtension(**kwargs)

```

It turns something like `[[ versionadded 1.8.0 ]]` into *Added in version 1.8.0*, or `[[ versionchanged 1.8.0 ]]` => *Changed in version 1.8.0*. My regex writing skills are not great, so hopefully that is understandable

**Comment by foosel** [comment]
I thought I'd already closed this, because your example worked beautifully and that's how it's done now! Thanks!
